export const notifications = [
    {
        id: 1,
        type: "message",
        unread: true,
        user: "Darren Smith",
        text: "sent you a message",
        preview: "Hey, did you see the new assignment posted?",
        time: "2 min ago",
        avatar: "DS",
    },
    {
        id: 2,
        type: "comment",
        unread: true,
        user: "Arin Gansihram",
        text: "commented on your post",
        preview: "This is actually really insightful, thanks for sharing!",
        time: "1 hr ago",
        avatar: "AG",
    },
    {
        id: 3,
        type: "connect",
        unread: true,
        user: "Juliet Den",
        text: "wants to connect with you",
        preview: "2nd year, Computer Science • 4 mutual connections",
        time: "2 hrs ago",
        avatar: "JD",
    },
    {
        id: 4,
        type: "academic",
        unread: false,
        user: "CSC 301 Study Group",
        text: "you were added to a group",
        preview: "12 members • Dr. Adeyemi created this group",
        time: "Yesterday",
        avatar: "CS",
    },
    {
        id: 5,
        type: "marketplace",
        unread: false,
        user: "Tolu Kadiri",
        text: "enquired about your listing",
        preview: "Is the MacBook Pro still available?",
        time: "2 days ago",
        avatar: "TK",
    },
    {
        id: 6,
        type: "newsroom",
        unread: false,
        user: "Emeka M.",
        text: "liked your post",
        preview: "Your post about the hackathon got 12 likes",
        time: "2 days ago",
        avatar: "EM",
    },
]