import calcTextImg from "../../assets/marketplace/calctext.jpg";
import drinksImg from "../../assets/marketplace/drinks.jpg";
import fabImg from "../../assets/marketplace/fab.jpg";
import fanImg from "../../assets/marketplace/fan.jpg";
import perfumeImg from "../../assets/marketplace/perfume.jpg";
import rancImg from "../../assets/marketplace/ranc.jpg";
import sneakersImg from "../../assets/marketplace/sneakers.jpg";

export const categoriesByType = {
  goods: [
    "Food",
    "Educational Materials",
    "Appliances",
    "Beauty",
    "Clothing",
    "Tech",
    "Accessories",
    "Health",
    "Home & Decor",
    "Sports",
    "Stationery",
    "Other",
  ],
  services: [
    "Delivery",
    "Hair",
    "Lashes",
    "Tutoring",
    "Laundry",
    "Cleaning",
    "Photography",
    "Design",
    "Repairs",
    "Transport",
    "Events",
    "Other",
  ],
};

export const storeContacts = {
  "Caseyâ€™s Store": [
    { type: "WhatsApp", value: "+234 803 111 2200" },
    { type: "Phone", value: "0703 111 2200" },
    { type: "Instagram", value: "@caseys_store" },
  ],
  "Gbemiâ€™s Kitchen": [
    { type: "WhatsApp", value: "+234 806 445 9001" },
    { type: "Phone", value: "0810 445 9001" },
    { type: "Instagram", value: "@gbemiskitchen" },
  ],
  "Titiâ€™s Mini Mart": [
    { type: "Phone", value: "0902 330 5566" },
    { type: "WhatsApp", value: "+234 902 330 5566" },
  ],
  "Mikeâ€™s Bookshop": [
    { type: "WhatsApp", value: "+234 815 002 7788" },
    { type: "Instagram", value: "@mikesbooks" },
  ],
  "Sadeâ€™s Appliances": [
    { type: "Phone", value: "0807 880 1144" },
    { type: "WhatsApp", value: "+234 807 880 1144" },
  ],
  "Joshâ€™s Tech Desk": [
    { type: "WhatsApp", value: "+234 812 442 3300" },
    { type: "Email", value: "joshtechdesk@studenthub.ng" },
    { type: "Instagram", value: "@joshtechdesk" },
  ],
  "Titiâ€™s Braids": [
    { type: "WhatsApp", value: "+234 706 551 7788" },
    { type: "Snapchat", value: "titi.braids" },
  ],
  "Kemiâ€™s Kicks": [
    { type: "Instagram", value: "@kemiskicks" },
    { type: "Phone", value: "0815 662 0099" },
  ],
  "Simiâ€™s Dispatch": [
    { type: "WhatsApp", value: "+234 813 900 2211" },
    { type: "Phone", value: "0813 900 2211" },
  ],
  "Tundeâ€™s Treats": [
    { type: "Instagram", value: "@tundestreats" },
    { type: "Phone", value: "0704 112 3344" },
  ],
  "Kemiâ€™s Beauty Bar": [
    { type: "WhatsApp", value: "+234 809 500 7788" },
    { type: "Instagram", value: "@kemisbeautybar" },
  ],
};

export const marketplaceItems = [
  {
    id: "bgh-delivery",
    title: "BGH delivery",
    desc: "Delivery from BGH to rooms.",
    price: "N1200",
    time: "50 mins ago",
    added: "Today",
    orders: 12,
    visits: 140,
    rating: 4.6,
    locations: ["Diamond Hall", "Sapphire Hall", "Crystal Hall", "Platinum Hall"],
    storeName: "Casey’s Store",
    type: "services",
    category: "Delivery",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    storeRating: 4.4,
    storeFavorites: 86,
    storeReviews: [
      { name: "Jesse L.", text: "Quick and reliable delivery." },
      { name: "Tomi J.", text: "Always on time." },
    ],
  },
  {
    id: "rice-and-chicken",
    title: "Rice and Chicken",
    desc: "One plate of jollof rice with one piece of chicken.",
    price: "N4000",
    time: "2 hours ago",
    added: "Today",
    orders: 48,
    visits: 360,
    rating: 4.8,
    locations: ["Emerald Hall"],
    storeName: "Gbemi’s Kitchen",
    type: "goods",
    category: "Food",
    image: rancImg,
    frequent: true,
    storeRating: 4.8,
    storeFavorites: 214,
    storeReviews: [
      { name: "Mira K.", text: "Best jollof on campus." },
      { name: "Ayo O.", text: "Tasty and consistent." },
    ],
    reviews: [
      { name: "Mira K.", text: "Tastes great, will order again." },
      { name: "Tomi J.", text: "Portion size is solid for the price." },
    ],
  },
  {
    id: "drinks-pack",
    title: "Drinks",
    desc: "Fanta, Sprite, Schweppes and Coke",
    price: "N500",
    time: "Yesterday",
    added: "Yesterday",
    orders: 72,
    visits: 520,
    rating: 4.7,
    locations: ["Queen Esther Hall", "FAD Hall"],
    storeName: "Titi’s Mini Mart",
    type: "goods",
    category: "Food",
    image: drinksImg,
    storeRating: 4.5,
    storeFavorites: 142,
    storeReviews: [{ name: "Ruth A.", text: "Fast delivery and cold drinks." }],
    reviews: [{ name: "Ayo O.", text: "Cold and quick delivery." }],
  },
  {
    id: "calculus-textbook-bundle",
    title: "Calculus Textbook Bundle",
    desc: "3 books, good condition. Includes worked examples.",
    price: "N8500",
    time: "3 hours ago",
    added: "Today",
    orders: 9,
    visits: 120,
    rating: 4.5,
    locations: ["Nyberg Hall", "Winslow Hall"],
    storeName: "Mike’s Bookshop",
    type: "goods",
    category: "Educational Materials",
    image: calcTextImg,
    frequent: true,
    storeRating: 4.6,
    storeFavorites: 97,
    storeReviews: [{ name: "Sade A.", text: "Great deals on textbooks." }],
    reviews: [{ name: "Sade A.", text: "Very helpful for exam prep." }],
  },
  {
    id: "room-fan",
    title: "Room Fan",
    desc: "Standing fan, barely used.",
    price: "N18000",
    time: "1 day ago",
    added: "Yesterday",
    orders: 3,
    visits: 64,
    rating: 4.2,
    locations: ["Platinum Hall"],
    storeName: "Sade’s Appliances",
    type: "goods",
    category: "Appliances",
    image: fanImg,
    storeRating: 4.2,
    storeFavorites: 54,
    storeReviews: [{ name: "Kunle P.", text: "Fan was clean and works well." }],
  },
  {
    id: "laptop-cleanup",
    title: "Laptop Cleanup",
    desc: "PC cleanup, antivirus, and speed boost.",
    price: "N3000",
    time: "5 hours ago",
    added: "Today",
    orders: 21,
    visits: 180,
    rating: 4.7,
    locations: ["Ogden Hall", "Gideon Troopers Hall"],
    storeName: "Josh’s Tech Desk",
    type: "services",
    category: "Repairs",
    image: "https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=400&q=80",
    storeRating: 4.7,
    storeFavorites: 121,
    storeReviews: [{ name: "Zara T.", text: "Laptop is much faster now." }],
  },
  {
    id: "hair-braiding",
    title: "Hair Braiding",
    desc: "Neat braids with extensions. Book ahead.",
    price: "N8000",
    time: "Yesterday",
    added: "Yesterday",
    orders: 15,
    visits: 150,
    rating: 4.6,
    locations: ["Queen Esther Hall", "Welch Hall"],
    storeName: "Titi’s Braids",
    type: "services",
    category: "Hair",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80",
    storeRating: 4.6,
    storeFavorites: 88,
    storeReviews: [{ name: "Lola S.", text: "Neat braids, nice service." }],
  },
  {
    id: "sneakers",
    title: "Sneakers",
    desc: "Size 42, clean and comfy.",
    price: "N15000",
    time: "2 days ago",
    added: "2 days ago",
    orders: 5,
    visits: 90,
    rating: 4.3,
    locations: ["White Hall", "Nelson Mandela Hall"],
    storeName: "Kemi’s Kicks",
    type: "goods",
    category: "Clothing",
    image: sneakersImg,
    storeRating: 4.3,
    storeFavorites: 73,
    storeReviews: [{ name: "Ola M.", text: "Sneakers are clean and comfy." }],
  },
  {
    id: "busa-delivery",
    title: "BUSA Delivery",
    desc: "Delivery from BUSA to rooms.",
    price: "N700",
    time: "1 hour ago",
    added: "Today",
    orders: 30,
    visits: 260,
    rating: 4.8,
    locations: ["FAD Hall", "Queen Esther Hall"],
    storeName: "Simi’s Dispatch",
    type: "services",
    category: "Delivery",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
    frequent: true,
    storeRating: 4.8,
    storeFavorites: 190,
    storeReviews: [{ name: "Teni A.", text: "Super fast delivery." }],
  },
  {
    id: "fab-biscuit",
    title: "Fab Biscuit",
    desc: "Chocolate fab",
    price: "N650",
    time: "2 days ago",
    added: "2 days ago",
    orders: 11,
    visits: 130,
    rating: 4.1,
    locations: ["Samuel Akande Hall", "Ameyo Hall"],
    storeName: "Tunde’s Treats",
    type: "goods",
    category: "Food",
    image: fabImg,
    storeRating: 4.1,
    storeFavorites: 46,
    storeReviews: [{ name: "Nora I.", text: "Tasty and affordable." }],
  },
  {
    id: "perfume",
    title: "Perfume",
    desc: "1 bottle of perfume 100ml, top notes coffee and vanilla",
    price: "N25000",
    time: "8 hours ago",
    added: "Today",
    orders: 6,
    visits: 82,
    rating: 4.4,
    locations: ["White Hall", "Neal Wilson Hall"],
    storeName: "Kemi’s Beauty Bar",
    type: "goods",
    category: "Beauty",
    image: perfumeImg,
    frequent: true,
    storeRating: 4.5,
    storeFavorites: 132,
    storeReviews: [{ name: "Ife B.", text: "Smells amazing, lasting scent." }],
  },
];

export const dummyProducts = [
  { id: "d1", name: "Jollof Rice & Chicken", description: "One plate of smoky jollof rice with a piece of chicken.", price: 4000, type: "goods", category: "Food", locations: ["Emerald Hall", "Ameyo Hall"], images: [rancImg], store: { id: "ds1", name: "Gbemi's Kitchen", contacts: [{ type: "WhatsApp", value: "+234 806 445 9001" }] } },
  { id: "d2", name: "Drinks Pack", description: "Fanta, Sprite, Schweppes and Coke — chilled.", price: 500, type: "goods", category: "Food", locations: ["Queen Esther Hall", "FAD Hall"], images: [drinksImg], store: { id: "ds2", name: "Titi's Mini Mart", contacts: [{ type: "Phone", value: "0902 330 5566" }] } },
  { id: "d3", name: "Calculus Textbook Bundle", description: "3 books in good condition. Includes worked examples.", price: 8500, type: "goods", category: "Educational Materials", locations: ["Nyberg Hall", "Winslow Hall"], images: [calcTextImg], store: { id: "ds3", name: "Mike's Bookshop", contacts: [{ type: "WhatsApp", value: "+234 815 002 7788" }] } },
  { id: "d4", name: "Standing Fan", description: "Barely used standing fan, works perfectly.", price: 18000, type: "goods", category: "Appliances", locations: ["Platinum Hall"], images: [fanImg], store: { id: "ds4", name: "Sade's Appliances", contacts: [{ type: "Phone", value: "0807 880 1144" }] } },
  { id: "d5", name: "Perfume 100ml", description: "Top notes: coffee and vanilla. Long lasting.", price: 25000, type: "goods", category: "Beauty", locations: ["White Hall", "Neal Wilson Hall"], images: [perfumeImg], store: { id: "ds5", name: "Kemi's Beauty Bar", contacts: [{ type: "Instagram", value: "@kemisbeautybar" }] } },
  { id: "d6", name: "Sneakers (Size 42)", description: "Clean and comfy sneakers, barely worn.", price: 15000, type: "goods", category: "Clothing", locations: ["White Hall", "Nelson Mandela Hall"], images: [sneakersImg], store: { id: "ds6", name: "Kemi's Kicks", contacts: [{ type: "Instagram", value: "@kemiskicks" }] } },
  { id: "d7", name: "Fab Biscuit", description: "Chocolate fab biscuit, sweet and crunchy.", price: 650, type: "goods", category: "Food", locations: ["Samuel Akande Hall", "Ameyo Hall"], images: [fabImg], store: { id: "ds7", name: "Tunde's Treats", contacts: [{ type: "Phone", value: "0704 112 3344" }] } },
  { id: "d8", name: "BGH Delivery", description: "Delivery from BGH to your room.", price: 1200, type: "services", category: "Delivery", locations: ["Diamond Hall", "Sapphire Hall", "Crystal Hall"], images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"], store: { id: "ds8", name: "Casey's Store", contacts: [{ type: "WhatsApp", value: "+234 803 111 2200" }] } },
  { id: "d9", name: "Laptop Cleanup", description: "PC cleanup, antivirus install and speed boost.", price: 3000, type: "services", category: "Repairs", locations: ["Ogden Hall", "Gideon Troopers Hall"], images: ["https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=400&q=80"], store: { id: "ds9", name: "Josh's Tech Desk", contacts: [{ type: "WhatsApp", value: "+234 812 442 3300" }] } },
  { id: "d10", name: "Hair Braiding", description: "Neat braids with extensions. Book ahead.", price: 8000, type: "services", category: "Hair", locations: ["Queen Esther Hall", "Welch Hall"], images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80"], store: { id: "ds10", name: "Titi's Braids", contacts: [{ type: "WhatsApp", value: "+234 706 551 7788" }] } },
  { id: "d11", name: "BUSA Delivery", description: "Delivery from BUSA to your hall.", price: 700, type: "services", category: "Delivery", locations: ["FAD Hall", "Queen Esther Hall"], images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80"], store: { id: "ds11", name: "Simi's Dispatch", contacts: [{ type: "WhatsApp", value: "+234 813 900 2211" }] } },
  { id: "d12", name: "Laundry Service", description: "Wash, dry and fold. 24hr turnaround.", price: 2500, type: "services", category: "Laundry", locations: ["Havillah Hall", "Emerald Hall"], images: ["https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=400&q=80"], store: { id: "ds12", name: "Fresh Wash Co.", contacts: [{ type: "WhatsApp", value: "+234 810 000 1234" }] } },
];

export const dummyFavouriteStores = [
  { id: "fs1", name: "Gbemi's Kitchen", type: "goods", image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&q=80" },
  { id: "fs2", name: "Kemi's Beauty Bar", type: "goods", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&q=80" },
  { id: "fs3", name: "Simi's Dispatch", type: "services", image: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=300&q=80" },
  { id: "fs4", name: "Josh's Tech Desk", type: "services", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&q=80" },
  { id: "fs5", name: "Titi's Mini Mart", type: "goods", image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&q=80" },
  { id: "fs6", name: "Mike's Bookshop", type: "goods", image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&q=80" },
];
