import calcTextImg from "../../assets/marketplace/calctext.jpg";
import drinksImg from "../../assets/marketplace/drinks.jpg";
import fabImg from "../../assets/marketplace/fab.jpg";
import fanImg from "../../assets/marketplace/fan.jpg";
import perfumeImg from "../../assets/marketplace/perfume.jpg";
import rancImg from "../../assets/marketplace/ranc.jpg";
import sneakersImg from "../../assets/marketplace/sneakers.jpg";

export const categoriesByType = {
  goods: [
    "Food",
    "Educational Materials",
    "Appliances",
    "Beauty",
    "Clothing",
    "Tech",
    "Accessories",
    "Health",
    "Home & Decor",
    "Sports",
    "Stationery",
    "Other",
  ],
  services: [
    "Delivery",
    "Hair",
    "Lashes",
    "Tutoring",
    "Laundry",
    "Cleaning",
    "Photography",
    "Design",
    "Repairs",
    "Transport",
    "Events",
    "Other",
  ],
};

export const marketplaceItems = [
  {
    id: "bgh-delivery",
    title: "BGH delivery",
    desc: "Delivery from BGH to rooms.",
    price: "N1200",
    time: "50 mins ago",
    added: "Today",
    orders: 12,
    visits: 140,
    rating: 4.6,
    locations: ["Diamond Hall", "Sapphire Hall", "Crystal Hall", "Platinum Hall"],
    storeName: "Casey’s Store",
    type: "services",
    category: "Delivery",
    image: null,
  },
  {
    id: "rice-and-chicken",
    title: "Rice and Chicken",
    desc: "One plate of jollof rice with one piece of chicken.",
    price: "N4000",
    time: "2 hours ago",
    added: "Today",
    orders: 48,
    visits: 360,
    rating: 4.8,
    locations: ["Emerald Hall"],
    storeName: "Gbemi’s Kitchen",
    type: "goods",
    category: "Food",
    image: rancImg,
    frequent: true,
    reviews: [
      { name: "Mira K.", text: "Tastes great, will order again." },
      { name: "Tomi J.", text: "Portion size is solid for the price." },
    ],
  },
  {
    id: "drinks-pack",
    title: "Drinks",
    desc: "Fanta, Sprite, Schweppes and Coke",
    price: "N500",
    time: "Yesterday",
    added: "Yesterday",
    orders: 72,
    visits: 520,
    rating: 4.7,
    locations: ["Queen Esther Hall", "FAD Hall"],
    storeName: "Titi’s Mini Mart",
    type: "goods",
    category: "Food",
    image: drinksImg,
    reviews: [{ name: "Ayo O.", text: "Cold and quick delivery." }],
  },
  {
    id: "calculus-textbook-bundle",
    title: "Calculus Textbook Bundle",
    desc: "3 books, good condition. Includes worked examples.",
    price: "N8500",
    time: "3 hours ago",
    added: "Today",
    orders: 9,
    visits: 120,
    rating: 4.5,
    locations: ["Nyberg Hall", "Winslow Hall"],
    storeName: "Mike’s Bookshop",
    type: "goods",
    category: "Educational Materials",
    image: calcTextImg,
    frequent: true,
    reviews: [{ name: "Sade A.", text: "Very helpful for exam prep." }],
  },
  {
    id: "room-fan",
    title: "Room Fan",
    desc: "Standing fan, barely used.",
    price: "N18000",
    time: "1 day ago",
    added: "Yesterday",
    orders: 3,
    visits: 64,
    rating: 4.2,
    locations: ["Platinum Hall"],
    storeName: "Sade’s Appliances",
    type: "goods",
    category: "Appliances",
    image: fanImg,
  },
  {
    id: "laptop-cleanup",
    title: "Laptop Cleanup",
    desc: "PC cleanup, antivirus, and speed boost.",
    price: "N3000",
    time: "5 hours ago",
    added: "Today",
    orders: 21,
    visits: 180,
    rating: 4.7,
    locations: ["Ogden Hall", "Gideon Troopers Hall"],
    storeName: "Josh’s Tech Desk",
    type: "services",
    category: "Repairs",
    image: null,
  },
  {
    id: "hair-braiding",
    title: "Hair Braiding",
    desc: "Neat braids with extensions. Book ahead.",
    price: "N8000",
    time: "Yesterday",
    added: "Yesterday",
    orders: 15,
    visits: 150,
    rating: 4.6,
    locations: ["Queen Esther Hall", "Welch Hall"],
    storeName: "Titi’s Braids",
    type: "services",
    category: "Hair",
    image: null,
  },
  {
    id: "sneakers",
    title: "Sneakers",
    desc: "Size 42, clean and comfy.",
    price: "N15000",
    time: "2 days ago",
    added: "2 days ago",
    orders: 5,
    visits: 90,
    rating: 4.3,
    locations: ["White Hall", "Nelson Mandela Hall"],
    storeName: "Kemi’s Kicks",
    type: "goods",
    category: "Clothing",
    image: sneakersImg,
  },
  {
    id: "busa-delivery",
    title: "BUSA Delivery",
    desc: "Delivery from BUSA to rooms.",
    price: "N700",
    time: "1 hour ago",
    added: "Today",
    orders: 30,
    visits: 260,
    rating: 4.8,
    locations: ["FAD Hall", "Queen Esther Hall"],
    storeName: "Simi’s Dispatch",
    type: "services",
    category: "Delivery",
    image: null,
    frequent: true,
  },
  {
    id: "fab-biscuit",
    title: "Fab Biscuit",
    desc: "Chocolate fab",
    price: "N650",
    time: "2 days ago",
    added: "2 days ago",
    orders: 11,
    visits: 130,
    rating: 4.1,
    locations: ["Samuel Akande Hall", "Ameyo Hall"],
    storeName: "Tunde’s Treats",
    type: "goods",
    category: "Food",
    image: fabImg,
  },
  {
    id: "perfume",
    title: "Perfume",
    desc: "1 bottle of perfume 100ml, top notes coffee and vanilla",
    price: "N25000",
    time: "8 hours ago",
    added: "Today",
    orders: 6,
    visits: 82,
    rating: 4.4,
    locations: ["White Hall", "Neal Wilson Hall"],
    storeName: "Kemi’s Beauty Bar",
    type: "goods",
    category: "Beauty",
    image: perfumeImg,
    frequent: true,
  },
];
